### ISSUE TITLE
[arena/arrows] Allow arrow pickup.

### ISSUE THREAD

**Issue by sebasdt** [Despical/OITC#10]
Is there a way to enable pickup of arrows that have been shot from bows?
I think it would add another neat dimension to the game.

So when another player shoots the arrow with a bow and it gets stuck in a block. 
Another player should be able to pick up the same arrow.

Sorry for being so direct and thank you for your time in advance.

**Comment by Despical** [comment]
I'll add an option to enable it.

**Comment by sebasdt** [comment]
Hi I just got the time to test the new feature out.

Players dont receive the arrow when its picked up...
did you have this fault during testing?

**Comment by Despical** [comment]
> Hi I just got the time to test the new feature out.
> 
> Players dont receive the arrow when its picked up... altough it disapears from the ground. did you have this fault during testing?

Yes, it was working but the logic behind is reversed. Fixed in the latest commit, I'll release an update.
