### ISSUE TITLE
[Scoreboard] Ability to have a lobby scoreboard (when not queueing)

### ISSUE THREAD

**Issue by LawMixer** [Despical/OITC#12]
## Description of the new feature
Right now, there is no scoreboard in the lobby and it's looking kind of bland. I cannot add a scoreboard myself with a different plugin, because it might overlap each other and cause problems.

**Comment by Despical** [comment]
Put your arenas in a separate world and disable your scoreboard plugin in these worlds to avoid overlaps. This is the best choice otherwise it wouldn't be a good feature for a minigame plugin.
