### ISSUE TITLE
[Server support] Plugin fails to load on Paper 1.20.6

### ISSUE THREAD

**Issue by datatags** [Despical/OITC#15]
## Description of Issue
The plugin doesn't load correctly on Paper 1.20.6. (Issue is probably not present on Spigot 1.20.6)

## Steps to Reproduce
1. Install Paper 1.20.6 and this plugin
2. Start the server
3. Observe the console error and the plugin being disabled.

## OITC Version
2.5.8

## Server Version
```
This server is running Paper version 1.20.6-124-master@0fcf3e3 (2024-05-29T22:05:27Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
```

## Stack Trace/Log Files/Crash Reports
https://pastebin.com/JiVdG0c7

## Additional Information
Seems to be due to Paper's removal of CraftBukkit package relocation: https://forums.papermc.io/threads/1106/
Meaning there is no longer a component of the package that looks like `v1_20_R4`

**Comment by Despical** [comment]
Thank you for reporting. I have released an [update](https://www.spigotmc.org/resources/one-in-the-chamber.81185/), the issue should be resolved.
