### ISSUE TITLE
When player leaves whenever it transfer, it'll register as a player but godded mode

### ISSUE THREAD

**Issue by LawMixer** [Despical/OITC#3]
## Description of Issue
Whenever a player leaves the match and is teleported to the arena, they will in spectator mode and they will show up for all players; 

## Steps to Reproduce
1. Leave match when teleported; 

## OITC Version
Lastest

## Server Version
ImanitySpigot 1.8

## Stack Trace/Log Files/Crash Reports
none

## Additional Information 
None

**Comment by Despical** [comment]
I'll check. Thanks for reporting.

**Comment by Despical** [comment]
I've just tested on 1.19.4 Paper and haven't faced any issues. It's because 1.8 doesn't provide methods to hide and show players and it's also disabled in OITC for legacy versions such as 1.8

**Comment by Despical** [comment]
Enabled hiding players in legacy versions and also the issue has been fixed.
