### ISSUE TITLE
[Category] When queuing, all players are invisible except the ones in the queue

### ISSUE THREAD

**Issue by LawMixer** [Despical/OITC#5]
## Description of Issue
If possible, could we have a option to disable this?

## Steps to Reproduce
Self explanatory.
## OITC Version
Latest

## Server Version
1.8

**Comment by Despical** [comment]
There is an option called ```Hide-Players``` in the config file.

**Comment by Despical** [comment]
Any update? @LawMixer

**Comment by LawMixer** [comment]
Ah alright, thank you.
