### ISSUE TITLE
[Category] Ability to go over 10 

### ISSUE THREAD

**Issue by LawMixer** [Despical/OITC#6]
## Description of the new feature
You should be able to go over 10 players per match. There's one options that I think would be best, let me know if there's any, I'll love to give feedback.  

You could have it, so you can have it at like 10 spawns, but whatever you set, let's say a set 20 people can be in that arena, you can do 20 people and randomize the spawns within the 20 people playing;

**Comment by Despical** [comment]
For the further folks:

Minimum & maximum player amounts can be edited via arena editor. 
* ```/oitc edit <arena>```
