### ISSUE TITLE
[Category] When players queue with /oitc randomjoin, it will not put them in a mode that is queuing

### ISSUE THREAD

**Issue by LawMixer** [Despical/OITC#7]
## Description of Issue
When players queue with /oitc randomjoin, it will not put them in a mode that is queuing

## Steps to Reproduce
Two people join /oitc randomjoin, and it'll put them in separate modes; 

## OITC Version
Latest

## Server Version
ImanitySpigot 1.8.9

## Stack Trace/Log Files/Crash Reports
None provided. 

## Additional Information
Nothing.

**Comment by Despical** [comment]
Any update? @LawMixer

**Comment by LawMixer** [comment]
I'm having issues with /randomjoin not joining the highest playercount, which is a problem because I use an NPC instead of the signs.

**Comment by Despical** [comment]
You must use ```/oitc randomjoin``` instead of ```/randomjoin```.
