### ISSUE TITLE
[`Hide-Players`] Players can't see each other after game ends

### ISSUE THREAD

**Issue by datatags** [Despical/OITC#9]
## Description of Issue
If `Hide-Players` is enabled in the config, after a match ends, all players are teleported out to the set location, but players cannot see each other until relogging. `Hide-Players` says it hides in-game players from other online players, but once they're out in the lobby, they shouldn't be hidden anymore.

## Steps to Reproduce
1. Ensure `Hide-Players` is set to `true` in config.yml
1. Play a match normally
1. Wait to be teleported back to lobby
1. Observe that no players in lobby can see each other

## OITC Version
2.5.0

## Server Version
This server is running Paper version git-Paper-290 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: f186318)

## Stack Trace/Log Files/Crash Reports
N/A

## Additional Information
N/A

**Comment by Despical** [comment]
I'll check it, thanks for reporting.

**Comment by Despical** [comment]
Sorry for the delay. I'm studying Computer Engineering and I don't really have enough time to check issues.
